export const metadata = {
    title: 'demo-app',
    description: 'Generated by boilerplate',
};
export default function RootLayout({ children }) {
    return (<html lang="en">
      <body>{children}</body>
    </html>);
}
