name: Version Bump

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  bump:
    # Only run if the commit wasn't made by this action
  if: "!contains(github.event.head_commit.message, '[skip ci]')"
  runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        run: |
          npm version patch -m "chore(release): v%s [skip ci]"

      - name: Push changes and tags
        run: |
          git push --follow-tags